apiVersion: v1
kind: Namespace
metadata:
  name: doris
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fdb-kubernetes-operator-controller-manager
  namespace: doris
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fdb-kubernetes-operator-manager-role
rules:
- apiGroups: ["apps.foundationdb.org"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints", "persistentvolumeclaims", "configmaps", "secrets", "serviceaccounts"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["*"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fdb-kubernetes-operator-manager-rolebinding
subjects:
- kind: ServiceAccount
  name: fdb-kubernetes-operator-controller-manager
  namespace: doris
roleRef:
  kind: ClusterRole
  name: fdb-kubernetes-operator-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdb-kubernetes-operator-controller-manager
  namespace: doris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdb-kubernetes-operator
  template:
    metadata:
      labels:
        app: fdb-kubernetes-operator
    spec:
      serviceAccountName: fdb-kubernetes-operator-controller-manager
      containers:
      - name: manager
        image: foundationdb/fdb-kubernetes-operator:v1.12.0
        imagePullPolicy: Never
        args:
        - --enable-leader-election
        env:
        - name: WATCH_NAMESPACE
          value: ""
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
