apiVersion: apps.foundationdb.org/v1beta2
kind: FoundationDBCluster
metadata:
  name: doris-fdb
  namespace: doris
spec:
  version: 7.3.69
  routing:
    useDNSInClusterFile: true
  mainContainer:
    imageConfigs:
    - baseImage: foundationdb/foundationdb
      tag: 7.3.69
  sidecarContainer:
    imageConfigs:
    - baseImage: foundationdb/foundationdb
      tag: 7.3.69
  processes:
    general:
      podTemplate:
        spec:
          containers:
          - name: foundationdb
            volumeMounts:
            - name: data
              mountPath: /var/lib/foundationdb/data
            resources:
              requests:
                cpu: "500m"
                memory: "512Mi"
              limits:
                cpu: "1"
                memory: "1Gi"
          - name: foundationdb-kubernetes-sidecar
            volumeMounts:
            - name: data
              mountPath: /var/lib/foundationdb
          volumes:
          - name: data
            emptyDir: {}
    storage_1:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  databaseConfiguration:
    redundancy_mode: single
    storage_engine: ssd
  faultDomain:
    key: none
