apiVersion: v1
kind: ConfigMap
metadata:
  name: doris-recycler-config
  namespace: doris
  labels:
    app.kubernetes.io/component: recycler
data:
  recycler.conf: |
    brpc_listen_port = 5000
    brpc_num_threads = -1
    brpc_idle_timeout_sec = 30
    http_token = greedisgood9999
    log_dir = ./log/
    log_level = info
    log_size_mb = 1024
    log_filenum_quota = 10
    log_immediate_flush = false
